#!/bin/bash
set -euo pipefail
VERSION=${VERSION:-0.0.0}

build() {
    mkdir -p bin
    for f in cmd/*; do
        cmd="$(basename "$f")"
        out="bin/$cmd.$GOOS-$GOARCH"
        echo "Building $out" >&2
        rm -f "$out" "$out."*
        CGO_ENABLED=0 go build -o "$out" "./cmd/$cmd"
        bzip2 -k "$out"
    done
}


GOOS=linux  GOARCH=amd64 build
GOOS=linux  GOARCH=arm64 build

GOOS=darwin GOARCH=amd64 build
GOOS=darwin GOARCH=arm64 build

GOOS=windows GOARCH=amd64 build

./mkwheel/mkwheel.sh "$VERSION" dist/