FROM {{ .BaseImage.Registry }}/{{ .BaseImage.Image }}:{{ .Python.Version }}

RUN apt-get -qy update && \
  apt-get -qy install libgl1 && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

{{ if not .Secret }}
COPY . .
ENTRYPOINT [ "python", "/app/agent.py" ]
{{ end }}
