#!/bin/bash
set -euo pipefail

main() {
    local name="$1"; shift
    local version="$1"; shift
    local dest; dest="$(realpath "$1")"; shift
    local readme; readme="$(realpath "$1")"; shift
    local platform="$1"; shift
    local binary; binary="$(realpath "$1")"; shift

    local source
    source="$(dirname "$(realpath -s "$0")")/$name"

    local tempdir
    tempdir="$(mktemp -d)"
    pushd "$tempdir"

    local dist_info="$name-$version.dist-info"
    mkdir -p "$dist_info"

    local tag="py3-none-$platform"

    # METADATA
    VERSION="$version" envsubst '$VERSION' < "$source/metadata.envsubst" > "$dist_info/METADATA"
    cat "$readme" >> "$dist_info/METADATA"

    # WHEEL
    TAG=$tag envsubst '$TAG' < "$source/wheel.envsubst" > "$dist_info/WHEEL"

    # Content
    mkdir -p "$name"
    touch "$name/__init__.py"
    cat <<EOF > "$name/__main__.py"
import os, sys, subprocess
sys.exit(subprocess.call([
	os.path.join(os.path.dirname(__file__), "$name"),
	*sys.argv[1:]
]))
EOF
    cp "$binary" "$name/$name"
    cat <<EOF > "$dist_info/entry_points.txt"
[console_scripts]
$name = $name:__main__
EOF
    find "$name" -type f | while read -r f; do
        sha=$(openssl dgst -sha256 -binary <<< "$f" | openssl base64 -A)
        size=$(stat -c '%s' "$f")
        echo "$f,sha256=$sha,$size" >> "$dist_info/RECORD"
    done
    zip -r "$dest/$name-$version-$tag.whl" .
    popd
}

main "$@"