on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: golangci/golangci-lint-action@v3

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: ./build-release-binaries
    - uses: actions/upload-artifact@v3
      with:
        path: bin/*
    - run: go test -v ./...
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: xx